### PR TITLE
add multiple maps

### PR DESCRIPTION
**Pull request by sidkans**
Update maze generation to use Prim's Algorithm. so the map is generated dynamically each time the program is run.

### CODE REVIEW

**Comment by 0xIcarus** [comment]
@sidkans can you update it to use a different map everytime the engine runs? Ideally I would want you to implement a system where the map changes after the player reaches a certain point in the map-- like the original doom game. From what I can see right now, it looks like it's just generating a single static map?

**Comment by sidkans** [comment]
@Icarus131 I had used a random DFS which gave me max recursion errors . Fixed it now i shall check it once to see if i can notice any changes in map generation. Another issue with previous code i noticed while waiting was borders were not respected that should also be fixed now.

**Comment by 0xIcarus** [comment]
I'd rather not focus on the algorithm used to generate the map-- that's up to you. I want you to implement a system where the maps change dynamically, hence requiring a generator to provide multiple random binary grids. Let me know if you dont understand still.

**Comment by 0xIcarus** [comment]
!bounty 510

**Comment by DedLad** [comment]
!bounty 560

**Pull request closed without merging**
